services:
  postgres:
    image: postgres:15
    container_name: dgii-postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=dgii-api
    ports:
      - 5432:5432
    healthcheck:
      test: nc -z localhost 5432
